version: 0.2
phases:
  install:
    commands:
      - echo "Installing Terraform ${TF_VERSION} on Ubuntu..."
      - apt-get update && apt-get install -y unzip curl
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version
      - pip install pyyaml
  pre_build:
    commands:
      - echo "Fetching secrets from Secrets Manager..."
      - aws secretsmanager get-secret-value --secret-id ${AWS_SECRET_NAME} --query SecretString --output text | jq . > terraform.tfvars.json || { echo "Failed to fetch secret"; exit 1; }
      - terraform init -input=false -backend-config="bucket=${PROJECT_NAME}-serverless-infra-terraform-state"
      - aws s3 cp s3://${PROJECT_NAME}-infra-terraform-state/tf_outputs.json .
      - python3 values-gen.py --secret-file=terraform.tfvars.json --var-file=tf_outputs.json --out-file=terraform.tfvars --out-case=snake
  build:
    commands:
      - echo "Running Terraform Plan..."
      - terraform plan -out=tfplan -input=false -var-file=terraform.tfvars.json
  post_build:
    commands:
      - rm -f terraform.tfvars.json terraform.tfvars.yaml
artifacts:
  files:
    - tfplan
    - modules/lambda/rds_scheduler/rds_scheduler.zip
    - .terraform.lock.hcl
